### PR TITLE
#158792524 Design mockups 

### PR DESCRIPTION
**Pull request by NabunyaLilian**
**What does this PR do?**

Implements the design of mockups for converge level up project.

**Description of Task to be completed?**

- Create mockup for list of java developers
- Create mockup for developer profile
- Create mockup for share profile options
- Link mockups 

**What are the relevant pivotal tracker stories?**

[#158792524](https://www.pivotaltracker.com/story/show/158792524)

**Demo**
Screen 4

**Screenshots**
- List View

Screen 1

- Detail View

Screen 4

- Share View
Screen 3

### CODE REVIEW

**Comment by johngorithm** [comment]
Good Job @NabunyaLilian. 

**List View**
* Remove the `Github Username` tag to each of the list item. The user's username alone is enough to identify the him/her


**Detail View**
* This view require more display items than you supplied. Review this story's description for more information on what is expected. I will equally encourage you to add more fields like `followers`, `following`, `public repos` and so on ... in accordance with your capacity.

**Comment by johngorithm** [comment]
You detail view `tool bar` does not exhibit the same properties as that in the main list view in terms of `color theme`. Kindly, fix this...

**Comment by johngorithm** [comment]
Consider having a `share icon` on the **tool Bar** to handle share functionality. You will learn more by doing this and also you will improve user experience in that regards.

**Comment by johngorithm** [comment]
It is good you have a dynamic GIF image on your PR description. This is really helpful and I do encourage you to continue in that regard. However, this story required that you have static images of the individual designs on your work output. This story equally expects that you link those images to your project's `README.md` file. Kindly link all the designs to README.md file ...

👍

**Comment by NabunyaLilian** [comment]
Thanks for the feedback @johngorithm , let me work on it.

**Comment by johngorithm** [comment]
Some more:
Kindly align the `usernames` to the vertical center of the `images`.

**Comment by johngorithm** [comment]
- Also, fix alignment issues on the detail view. The numbers should equally maintain a vertical center alignment with the text beside them.
- Fix alignment issues on the ToolBar.
- Let's have a field name for the `bio`
- Remove the scroll bar as that won't be visible in the real app
- The following should be visible in your design along with the ones you have currently:

```
User’s profile image
User’s GitHub username
User's Organisation
```

Good Job 👍

**Comment by NabunyaLilian** [comment]
okay @johngorithm thanks for the feedback, I'm done implementing it.

**Review by johngorithm — APPROVED** [review]
Good Job on this @NabunyaLilian 
LGTM

I am merging this.

**Pull request merged**
